modLoader="javafml"
loaderVersion="[1,)"
license="All Rights Reserved"

[[mods]]
modId="solaris_loader"
version="0.1.0"
displayName="Solaris Loader"
description='''Solaris client-bundle configuration transport.'''

[[dependencies.solaris_loader]]
modId="neoforge"
type="required"
versionRange="[26.1.2.76,)"
ordering="NONE"
side="CLIENT"

[[dependencies.solaris_loader]]
modId="minecraft"
type="required"
versionRange="[26.1.2]"
ordering="NONE"
side="CLIENT"

