modLoader="javafml"
loaderVersion="[64,)"
license="All Rights Reserved"
clientSideOnly=true

[[mods]]
modId="solaris_loader"
version="0.1.0"
displayName="Solaris Loader"
description='''Solaris client-bundle configuration transport.'''

[[dependencies.solaris_loader]]
modId="forge"
mandatory=true
versionRange="[64,)"
ordering="NONE"
side="CLIENT"

[[dependencies.solaris_loader]]
modId="minecraft"
mandatory=true
versionRange="[26.1.2,26.2,)"
ordering="NONE"
side="CLIENT"
